style: re-run prettier since it was not working
aws/aws-toolkit-vscode pull request #1836
Opened 2021-06-25 21:56 UTC by JadenSimon

Husky hooks weren't working for a month or so.

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-06-25 21:56 UTC, JadenSimon commented
/runintegrationtests

2021-06-25 23:57 UTC, justinmk3 approved these changes

2021-06-27 08:38 UTC, justinmk3 requested changes
since this is automated and can be easily re-run, let's wait until https://github.com/aws/aws-toolkit-vscode/pull/1833 and App Runner are merged

2021-06-30 17:24 UTC, JadenSimon commented
Will make a new one when stuff is merged.

2021-06-30 17:24 UTC, closed without merging